AWSTemplateFormatVersion: '2010-09-09'

Description: Using GitHub Actions to deploy CloudFormation stacks Demo

Resources:

  EC2RKE2Test0:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-022ab0f9e3b3697d3
      KeyName: mdd_key_2
      InstanceType: t3.large
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 32
          DeleteOnTermination: "true"
      NetworkInterfaces:
      - DeviceIndex: 0
        AssociatePublicIpAddress: true
        SubnetId: subnet-356f8c5c
        GroupSet:
        - sg-080e91dcf485a8c82
      Tags:
      - Key: "Name"
        Value: "rke2-ansible-automated-test-0"
      - Key: "Owner"
        Value: "rke2-ansible-github-actions"

  EC2RKE2Test1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-022ab0f9e3b3697d3
      KeyName: mdd_key_2
      InstanceType: t3.large
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 32
          DeleteOnTermination: "true"
      NetworkInterfaces:
      - DeviceIndex: 0
        AssociatePublicIpAddress: true
        SubnetId: subnet-356f8c5c
        GroupSet:
        - sg-080e91dcf485a8c82
      Tags:
      - Key: "Name"
        Value: "rke2-ansible-automated-test-1"
      - Key: "Owner"
        Value: "rke2-ansible-github-actions"

  EC2RKE2Test2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-022ab0f9e3b3697d3
      KeyName: mdd_key_2
      InstanceType: t3.large
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 32
          DeleteOnTermination: "true"
      NetworkInterfaces:
      - DeviceIndex: 0
        AssociatePublicIpAddress: true
        SubnetId: subnet-356f8c5c
        GroupSet:
        - sg-080e91dcf485a8c82
      Tags:
      - Key: "Name"
        Value: "rke2-ansible-automated-test-2"
      - Key: "Owner"
        Value: "rke2-ansible-github-actions"

  EC2RKE2Test3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-022ab0f9e3b3697d3
      KeyName: mdd_key_2
      InstanceType: t3.large
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 32
          DeleteOnTermination: "true"
      NetworkInterfaces:
      - DeviceIndex: 0
        AssociatePublicIpAddress: true
        SubnetId: subnet-356f8c5c
        GroupSet:
        - sg-080e91dcf485a8c82
      Tags:
      - Key: "Name"
        Value: "rke2-ansible-automated-test-3"
      - Key: "Owner"
        Value: "rke2-ansible-github-actions"

  EC2RKE2Test4:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-022ab0f9e3b3697d3
      KeyName: mdd_key_2
      InstanceType: t3.large
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 32
          DeleteOnTermination: "true"
      NetworkInterfaces:
      - DeviceIndex: 0
        AssociatePublicIpAddress: true
        SubnetId: subnet-356f8c5c
        GroupSet:
        - sg-080e91dcf485a8c82
      Tags:
      - Key: "Name"
        Value: "rke2-ansible-automated-test-4"
      - Key: "Owner"
        Value: "rke2-ansible-github-actions"