---
- name: Check for ironbank files in tarball_install dir
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/tarball_install/ironbank/{{ item.value | replace('/', '-') | replace(':', '-')  }}.tar"
  loop: "{{ ironbank_images_config | dict2items }}"
  register: ironbank_tars_on_disk

- name: debug stat 1
  ansible.builtin.debug:
    msg:
      - "{{ ironbank_tars_on_disk }}"
      - "{{ registry_config_file_path }}"

- name: Update config for ironbank images
  ansible.utils.update_fact:
    updates:
      - path: rke2_config.{{ item.item.key }}
        value: "{{ item.item.value }}"
  loop: "{{ ironbank_tars_on_disk.results }}"
  register: updated2
  # if airgap, only add images to config if they are on disk. otherwise always add them
  when: airgap_ironbank_images and item.stat.exists or not airgap_ironbank_images

- name: Print config before ironbank changes
  ansible.builtin.debug:
    var: rke2_config

# Note, that the update_fact call above creates a list of rke2_configs. one for each item in the list.
# so just merge back into 1 here. There's probably a better way to do this
- name: set rke2 config fact
  set_fact:
    rke2_config: "{{ updated2.results | json_query('[].rke2_config')  | combine }}"

- name: Print config after ironbank change
  ansible.builtin.debug:
    var: rke2_config

- name: Add ironbank images to needed directory if provided
  copy:
    src: "{{ item }}"
    dest: /var/lib/rancher/rke2/agent/images/
    mode: '0644'
  with_fileglob:
    - "{{ playbook_dir }}/tarball_install/ironbank/*.tar"
