name: Deploy CloudFormation Stacks

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: true
        default: "us-gov-east-1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cfn-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-gov-east-1"

      - name: Deploy CloudFormation Stacks
        id: rke2-ansible-cf-stack
        uses: aws-actions/aws-cloudformation-github-deploy
        with:
          name:  rke2-ansible-cf-stack
          template: testing/mike-template.yml

      - name: Delete Stack
        if: ${{ always() }}
        run: |
          aws cloudformation delete-stack --stack-name rke2-ansible-cf-stack;
          aws cloudformation wait stack-delete-complete --stack-name rke2-ansible-cf-stack;